// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp4iYLfasV3fpQSBa3QDPRXG9EDFJ1ZVU',
    appId: '1:926063384061:web:48315714a7a366f8fcf594',
    messagingSenderId: '926063384061',
    projectId: 'patientrecord-f654d',
    authDomain: 'patientrecord-f654d.firebaseapp.com',
    storageBucket: 'patientrecord-f654d.appspot.com',
    measurementId: 'G-GCWX6R8XM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCteaHUabSYbGFMC0Q1kgfzFrCsGc74wAg',
    appId: '1:926063384061:android:82ac2e6aad1a4ae3fcf594',
    messagingSenderId: '926063384061',
    projectId: 'patientrecord-f654d',
    storageBucket: 'patientrecord-f654d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdvwGoaoZx9xaGJSKh_r7ENB8_2s4zuo',
    appId: '1:926063384061:ios:c966e145696cb216fcf594',
    messagingSenderId: '926063384061',
    projectId: 'patientrecord-f654d',
    storageBucket: 'patientrecord-f654d.appspot.com',
    iosBundleId: 'com.example.patientRecordGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATdvwGoaoZx9xaGJSKh_r7ENB8_2s4zuo',
    appId: '1:926063384061:ios:792ec4c64b8326fefcf594',
    messagingSenderId: '926063384061',
    projectId: 'patientrecord-f654d',
    storageBucket: 'patientrecord-f654d.appspot.com',
    iosBundleId: 'com.example.patientRecordGenerator.RunnerTests',
  );
}
